# Generated by Django 3.1 on 2020-09-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='etime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='stime',
            field=models.DateTimeField(),
        ),
    ]
